on:
  push:
    branches:
    - 'master'
jobs:
  build-and-deploy:
    steps:
      - name: Build site
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: jekyll build 
